# Generated by Django 5.1.7 on 2025-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название')),
                ('price', models.IntegerField()),
                ('discounter_price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('feedbacks', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='apps_cardmo_price_75c285_idx'), models.Index(fields=['rating'], name='apps_cardmo_rating_c08c5a_idx')],
            },
        ),
    ]
